// GENERATED by scripts/rocketsites/gen-sitemap.js from PS_Isolated.spatial.json. Do not edit.
// Empty until the rocket sites are added to PS_Isolated: then run
// node scripts/rocketsites/gen-sitemap.js
// One entry per rocket site.
export interface SiloDef { siloId: number; x: number; y: number; z: number; }
export interface RadarPartDef { id: number; name: string; x: number; y: number; z: number; basis: number[]; }
// radarParts: the radar model's objects, the pivot (radarId) first; basis is the rest rotation, row-major.
// animZoneId: the radar only turns while a player is inside this trigger.
export interface SiteDef { n: number; team: number; zoneId: number; animZoneId: number; radarId: number; radarPos: [number, number, number];
    gridCentre: [number, number, number]; radarParts: RadarPartDef[]; silos: SiloDef[]; }
export const SITES: SiteDef[] = [];
